### ISSUE TITLE
Program stops functioning after successive timeouts 

### ISSUE THREAD

**Issue by egeldenhuys** [egeldenhuys/bandwidth-monitor#5]
Stops responding after the 4 time out errors:

```
Total Down (MiB): 157 (5 KiB/s)
Total Up (MiB)  : 712 (1 KiB/s)
Session (MiB)   : D: -2110 | U: 134

[ERROR] Request timed out while fetching statistics!
[ERROR] Request timed out while fetching statistics!
[ERROR] Request timed out while fetching statistics!
[ERROR] Request timed out while fetching statistics!
^CTraceback (most recent call last):
  File "bandwidth-monitor.py", line 240, in <module>
    main()
  File "bandwidth-monitor.py", line 73, in main
    time.sleep(timeDiff)
KeyboardInterrupt
```

**Comment by egeldenhuys** [comment]
Before:

```
Starting main sleep...
Stop main sleep.
Exit main loop
Enter main loop
Enter getStatistics()
200
OK
CaseInsensitiveDict({'transfer-encoding': 'chunked', 'expires': 'Thu, 26 Oct 1995 00:00:00 GMT', 'server': 'WebServer/1.0 UPnP/1.0', 'ext': '', 'pragma': 'no-cache', 'date': 'Sun, 12 Jun 2016 23:11:34 GMT', 'content-type': 'text/html'})
[]
[('C0', 'HASH'), ('C1', 'HASH')]
http://192.168.1.1/status/status_statistics.htm
Exit getStatistics()
Total Down (MiB): 12 (13 KiB/s)
Total Up (MiB)  : 1 (3 KiB/s)
Session (MiB)   : D: 0 | U: 0
```

After:

```
Starting main sleep...
Stop main sleep.
Exit main loop
Enter main loop
Enter getStatistics()
200
OK
CaseInsensitiveDict({'transfer-encoding': 'chunked', 'expires': 'Thu, 26 Oct 1995 00:00:00 GMT', 'server': 'WebServer/1.0 UPnP/1.0', 'ext': '', 'pragma': 'no-cache', 'date': 'Sat, 01 Jan 2000 00:00:32 GMT', 'content-type': 'text/html'})
[]
[('C0', 'HASH'), ('C1', 'HASH')]
http://192.168.1.1/login_security.html
Exit getStatistics()
```
